"""
Figure 3 — Adversity shifts SCAN's functional coupling toward sensorimotor systems
(Pillar 3). Each panel a separate vector PDF (+ PNG) under outputs/figures/nn/fig3/.

Code panels:
  fig3a_fc_betas     SCAN threat→FC β across its 14 partners (bidirectional shift)
  fig3b_spoke        radial spoke diagram of the same shift (toward warm / away cool)
  fig3c_struct_func  structure–function correspondence (encroach β vs FC β, Analysis F)

Workbench panels (separate): threat→SCAN-FC β surface (user renders); group-mean
SCAN-FC surface overlays (generated by gen_fc_groupmean_surfaces.py).
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

import figsrc as F

fs = F.fs
fs.set_style()
OUT = str(F.FIG_OUT / "fig3")
F.Path(OUT).mkdir(parents=True, exist_ok=True)

POS_COL = "#C44E52"   # coupling INCREASES with threat (toward)
NEG_COL = "#4C72B0"   # coupling DECREASES with threat (away)


def _star(q):
    return "***" if q < 1e-3 else "**" if q < 1e-2 else "*" if q < 0.05 else ""


def _scan_fc():
    """SCAN's 14 partner couplings: partner, beta, q (FDR-SCAN), sig."""
    d = pd.read_csv(F.TAB_DIR / "fc_lme_threat_baseline.csv")
    d = d[(d["net1"] == "SCAN") | (d["net2"] == "SCAN")].copy()
    d["partner"] = np.where(d["net1"] == "SCAN", d["net2"], d["net1"])
    return d[["partner", "beta", "q_fdr_scan", "sig_scan"]].reset_index(drop=True)


# ─────────────────────────────────────────────────────────────────────────────
# Panel 3a — SCAN threat→FC β across partners (bidirectional shift)
# ─────────────────────────────────────────────────────────────────────────────
def panel_fc_betas():
    d = _scan_fc().sort_values("beta", ascending=True).reset_index(drop=True)
    colors = [F.net_color(p) for p in d["partner"]]

    fig, ax = fs.figure("single", 78)
    ax.barh(range(len(d)), d["beta"].values, color=colors,
            edgecolor="black", linewidth=0.4)
    ax.axvline(0, color="black", lw=0.6)
    for i, r in d.iterrows():
        mk = _star(r["q_fdr_scan"])
        if mk:
            off = 0.001 if r["beta"] >= 0 else -0.001
            ax.text(r["beta"] + off, i, mk, ha="left" if r["beta"] >= 0 else "right",
                    va="center", fontsize=6)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels(d["partner"].values)
    ax.set_xlabel("Threat → SCAN coupling  (β)")
    # direction cues
    ax.text(0.98, 1.02, "→ stronger with threat", transform=ax.transAxes,
            ha="right", va="bottom", fontsize=5, color=POS_COL)
    ax.text(0.02, 1.02, "weaker ←", transform=ax.transAxes,
            ha="left", va="bottom", fontsize=5, color=NEG_COL)
    fs.despine(ax)
    fs.panel_label(ax, "a")
    fs.save(fig, "fig3a_fc_betas", outdir=OUT)
    nsig = int(d["sig_scan"].sum())
    print(f"  fig3a_fc_betas  {nsig}/14 FDR-sig; "
          f"top+ {d.iloc[-1]['partner']} {d.iloc[-1]['beta']:+.3f}, "
          f"top- {d.iloc[0]['partner']} {d.iloc[0]['beta']:+.3f}")


# ─────────────────────────────────────────────────────────────────────────────
# Panel 3b — radial spoke diagram of the SCAN connectivity shift
# ─────────────────────────────────────────────────────────────────────────────
def panel_spoke():
    d = _scan_fc().sort_values("beta", ascending=False).reset_index(drop=True)
    n = len(d)
    ang = np.pi / 2 - np.arange(n) / n * 2 * np.pi   # most + at top, clockwise
    bmax = d["beta"].abs().max()

    fig, ax = fs.figure(74, 74)
    ax.set_aspect("equal")
    ax.axis("off")
    for a, (_, r) in zip(ang, d.iterrows()):
        x, y = np.cos(a), np.sin(a)
        b, sig = r["beta"], bool(r["sig_scan"])
        col = POS_COL if b > 0 else NEG_COL
        ax.plot([0, x], [0, y], color=col, lw=0.5 + 3.2 * abs(b) / bmax,
                alpha=0.9 if sig else 0.28, solid_capstyle="round", zorder=2)
        ax.scatter(x, y, s=46, color=F.net_color(r["partner"]),
                   edgecolors="black", linewidths=0.4, zorder=4)
        ha = "center"
        ax.text(1.20 * x, 1.20 * y, r["partner"], ha=ha, va="center",
                fontsize=5.5, fontweight="bold" if sig else "normal")
    ax.scatter(0, 0, s=300, color=F.SCAN_COLOR, edgecolors="white",
               linewidths=0.7, zorder=5)
    ax.text(0, 0, "SCAN", ha="center", va="center", fontsize=4.3,
            color="white", fontweight="bold", zorder=6)
    ax.set_xlim(-1.4, 1.4)
    ax.set_ylim(-1.4, 1.4)
    # legend
    from matplotlib.lines import Line2D
    h = [Line2D([], [], color=POS_COL, lw=2, label="stronger with threat"),
         Line2D([], [], color=NEG_COL, lw=2, label="weaker with threat"),
         Line2D([], [], color="grey", lw=2, alpha=0.3, label="n.s. (FDR)")]
    ax.legend(handles=h, loc="lower center", bbox_to_anchor=(0.5, -0.13),
              fontsize=4.6, frameon=False, ncol=1, handlelength=1.2,
              labelspacing=0.25)
    fs.panel_label(ax, "b", x=0.0, y=1.0)
    fs.save(fig, "fig3b_spoke", outdir=OUT)
    print("  fig3b_spoke  done")


# ─────────────────────────────────────────────────────────────────────────────
# Panel 3b (alt) — chord diagram of the SCAN connectivity shift
#   Hub chord: SCAN sector + 14 partner sectors on a circle; ribbon width ∝ |β|,
#   warm = stronger with threat, cool = weaker. Same data as the spoke.
# ─────────────────────────────────────────────────────────────────────────────
def panel_chord():
    from matplotlib.path import Path
    from matplotlib.patches import PathPatch
    from matplotlib.lines import Line2D

    d = _scan_fc().copy()
    d["abeta"] = d["beta"].abs()
    d = d.sort_values("beta", ascending=False).reset_index(drop=True)   # warm→cool
    n = len(d)
    W = d["abeta"].sum()

    R = 1.0
    gap = np.deg2rad(2.2)                 # angular gap between adjacent sectors
    usable = 2 * np.pi - (n + 1) * gap    # SCAN sector + n partner sectors
    scale = (usable * 0.5) / W            # rad per unit |β| (partners share half)
    scan_span = usable * 0.5              # SCAN sector = the other half

    # SCAN sector centred at the bottom; partners fan over the top (CCW from its top edge)
    s_center = -np.pi / 2
    s0, s1 = s_center - scan_span / 2, s_center + scan_span / 2

    partner_arc, sub = [], []
    ang = s1 + gap                        # partner sectors march CCW over the top
    a = s1                                # SCAN sub-segments march CW down its arc
    for _, row in d.iterrows():
        w = row["abeta"] * scale
        partner_arc.append((ang, ang + w)); ang += w + gap
        sub.append((a - w, a)); a -= w

    fig, ax = fs.figure(74, 74)
    ax.set_aspect("equal"); ax.axis("off")

    def arc_pts(t0, t1, r, nseg=24):
        t = np.linspace(t0, t1, nseg)
        return np.c_[r * np.cos(t), r * np.sin(t)]

    def qbez(p0, p1, n=30):
        # quadratic Bézier p0→p1 with control at the origin (ribbon waist at centre)
        t = np.linspace(0, 1, n)[:, None]
        return (1 - t) ** 2 * np.asarray(p0) + t ** 2 * np.asarray(p1)

    # ribbons (drawn first, behind the sector arcs); node-end caps follow the
    # circle so wide sectors (SMD, SCAN) fill flush with no straight-chord gap
    for i, row in d.iterrows():
        a0, a1 = sub[i]; b0, b1 = partner_arc[i]
        col = POS_COL if row["beta"] > 0 else NEG_COL
        al = 0.80 if bool(row["sig_scan"]) else 0.18
        pA0 = (R * np.cos(a0), R * np.sin(a0)); pA1 = (R * np.cos(a1), R * np.sin(a1))
        pB0 = (R * np.cos(b0), R * np.sin(b0)); pB1 = (R * np.cos(b1), R * np.sin(b1))
        poly = np.vstack([
            arc_pts(a0, a1, R),     # arc across A  (a0 → a1)
            qbez(pA1, pB0),         # curved side   (a1 → b0)
            arc_pts(b0, b1, R),     # arc across B  (b0 → b1)
            qbez(pB1, pA0),         # curved side   (b1 → a0)
        ])
        ax.fill(poly[:, 0], poly[:, 1], facecolor=col, edgecolor="none",
                alpha=al, zorder=2)

    # node sectors (thick coloured arcs) + labels
    Rn = R + 0.012
    for i, row in d.iterrows():
        b0, b1 = partner_arc[i]
        pts = arc_pts(b0, b1, Rn)
        # PON's atlas colour is near-white; an outline on the thick chord arc
        # looked bad, so render pale networks a touch darker (still off-white)
        # with no stroke — it reads cleanly on white on its own.
        arc_col = "#DCDCDC" if row["partner"] in F.PALE_NETS else F.net_color(row["partner"])
        ax.plot(pts[:, 0], pts[:, 1], color=arc_col,
                lw=5.0, solid_capstyle="butt", zorder=4)
        mid = 0.5 * (b0 + b1); lr = R + 0.11   # push labels off the circle (breathing room)
        deg = np.degrees(mid) % 360                 # radial labels → no crowding
        rot, ha = (deg + 180, "right") if 90 < deg < 270 else (deg, "left")
        ax.text(lr * np.cos(mid), lr * np.sin(mid), row["partner"],
                rotation=rot, rotation_mode="anchor", ha=ha, va="center",
                fontsize=5.2,
                fontweight="bold" if bool(row["sig_scan"]) else "normal")
    pts = arc_pts(s0, s1, Rn)
    ax.plot(pts[:, 0], pts[:, 1], color=F.SCAN_COLOR, lw=5.0,
            solid_capstyle="butt", zorder=4)
    lr = R + 0.16
    ax.text(lr * np.cos(s_center), lr * np.sin(s_center), "SCAN", ha="center",
            va="center", fontsize=6, fontweight="bold", color=F.SCAN_COLOR)

    ax.set_xlim(-1.5, 1.5); ax.set_ylim(-1.5, 1.5)
    h = [Line2D([], [], color=POS_COL, lw=3, label="stronger with threat"),
         Line2D([], [], color=NEG_COL, lw=3, label="weaker with threat"),
         Line2D([], [], color="grey", lw=3, alpha=0.3, label="n.s. (FDR)")]
    ax.legend(handles=h, loc="lower center", bbox_to_anchor=(0.5, -0.10),
              fontsize=4.6, frameon=False, handlelength=1.2, labelspacing=0.25)
    fs.panel_label(ax, "b", x=0.0, y=1.0)
    fs.save(fig, "fig3b_chord", outdir=OUT)
    print("  fig3b_chord  done")


# ─────────────────────────────────────────────────────────────────────────────
# Panel 3c — structure–function correspondence (Analysis F)
# ─────────────────────────────────────────────────────────────────────────────
def panel_struct_func():
    d = pd.read_csv(F.TAB_DIR / "F_encroach_fc_correspondence.csv")
    x = d["threat_encroach_beta"].values
    y = d["threat_fc_beta"].values
    r, _ = pearsonr(x, y)

    fig, ax = fs.figure("single", 64)
    ax.axhline(0, color="#d6d6d6", lw=0.3, zorder=0)
    ax.axvline(0, color="#d6d6d6", lw=0.3, zorder=0)
    # regression line
    b1, b0 = np.polyfit(x, y, 1)
    xx = np.linspace(x.min(), x.max(), 50)
    ax.plot(xx, b0 + b1 * xx, color=F.GREY["line"], lw=0.9, zorder=2)
    # per-point label offsets to avoid collisions among close points
    off = {"VIS": (3, -7), "SML": (3, 3), "DMN": (3, 3), "Tpole": (-1, -8),
           "VAN": (3, -3), "MTL": (3, 3), "SMD": (-2, 6)}
    for _, row in d.iterrows():
        net = row["network"]
        ax.scatter(row["threat_encroach_beta"], row["threat_fc_beta"], s=24,
                   color=F.net_color(net), edgecolors="black",
                   linewidths=0.4, zorder=3)
        ax.annotate(net, (row["threat_encroach_beta"], row["threat_fc_beta"]),
                    xytext=off.get(net, (3, 3)), textcoords="offset points",
                    fontsize=4.6, color="black")
    ax.text(0.04, 0.96, f"r = {r:.2f}\nperm p = 0.029", transform=ax.transAxes,
            va="top", ha="left", fontsize=6)
    # call out the CO exception
    co = d[d["network"] == "CO"].iloc[0]
    ax.annotate("displaced but\ndecoupled",
                (co["threat_encroach_beta"], co["threat_fc_beta"]),
                xytext=(-6, -14), textcoords="offset points", fontsize=4.6,
                color=F.net_color("CO"), ha="center",
                arrowprops=dict(arrowstyle="-", lw=0.4, color=F.net_color("CO")))
    ax.set_xlabel("Threat → encroachment  (β, Fig. 2)")
    ax.set_ylabel("Threat → SCAN coupling  (β, Fig. 3)")
    # extend x-axis into the negative so the <0 point (MTL) and axis read clearly
    ax.set_xlim(-0.03, 0.12)
    ax.set_xticks([-0.025, 0.0, 0.025, 0.05, 0.075, 0.1])
    fs.despine(ax)
    fs.panel_label(ax, "c")
    fs.save(fig, "fig3c_struct_func", outdir=OUT)
    print(f"  fig3c_struct_func  r={r:.3f}")


if __name__ == "__main__":
    print("Building Figure 3 panels →", OUT)
    panel_fc_betas()
    panel_spoke()
    panel_chord()
    panel_struct_func()
    print("Done.")
